# Generated by Django 3.1.2 on 2021-06-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.IntegerField()),
                ('FirstName', models.CharField(blank=True, max_length=20, null=True)),
                ('LastName', models.CharField(blank=True, max_length=20, null=True)),
                ('Address', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.DecimalField(decimal_places=2, max_digits=13)),
                ('Date_start', models.DateTimeField(auto_now=True)),
                ('Is_active', models.BooleanField(verbose_name=False)),
                ('Base_fund', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
