# Generated by Django 3.1.2 on 2021-06-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Is_active',
            field=models.BooleanField(default=False),
        ),
    ]
