# Generated by Django 3.1.2 on 2021-06-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_system', '0002_auto_20210611_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_deposit', models.DateTimeField(auto_now=True)),
                ('Amount_deposit', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
