# Generated by Django 3.1.2 on 2021-06-13 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information_system', '0005_auto_20210612_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_repayment', models.DateTimeField(auto_now=True)),
                ('Amount_repayment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='information_system.members')),
            ],
            options={
                'verbose_name_plural': 'Repayments',
            },
        ),
    ]
